namespace :seed_data do
  task city: :environment do
     [
      {id: 1, name: "臺北市"},
      {id: 2, name: "新北市"},
      {id: 3, name: "基隆市"},
      {id: 4, name: "桃園市"},
      {id: 5, name: "新竹縣"},
      {id: 6, name: "苗栗縣"},
      {id: 7, name: "台中市"},
      {id: 8, name: "彰化縣"},
      {id: 9, name: "南投縣"},
      {id: 10, name: "雲林縣"},
      {id: 11, name: "嘉義縣"},
      {id: 12, name: "台南市"},
      {id: 13, name: "高雄市"},
      {id: 14, name: "屏東縣"},
      {id: 15, name: "宜蘭縣"},
      {id: 16, name: "花蓮縣"},
      {id: 17, name: "台東縣"},
      {id: 18, name: "澎湖縣"},
      {id: 19, name: "金門縣"},
      {id: 20, name: "馬祖縣"},
      {id: 21, name: "離島地區"}
     ].each do |city|
       City.create!(city)
     end
  end
  task area: :environment do
    [
      {id: 1 ,name: '中正區', zip_code: 100, city_id: 1},
      {id: 2 ,name: '大同區', zip_code: 103, city_id: 1},
      {id: 3 ,name: '中山區', zip_code: 104, city_id: 1},
      {id: 4 ,name: '松山區', zip_code: 105, city_id: 1},
      {id: 5 ,name: '大安區', zip_code: 106, city_id: 1},
      {id: 6 ,name: '萬華區', zip_code: 108, city_id: 1},
      {id: 7 ,name: '信義區', zip_code: 110, city_id: 1},
      {id: 8 ,name: '士林區', zip_code: 111, city_id: 1},
      {id: 9 ,name: '北投區', zip_code: 112, city_id: 1},
      {id: 10 ,name: '內湖區', zip_code: 114, city_id: 1},
      {id: 11 ,name: '南港區', zip_code: 115, city_id: 1},
      {id: 12 ,name: '文山區', zip_code: 116, city_id: 1},
      {id: 13 ,name: '其他',   zip_code: nil, city_id: 3},
      {id: 14 ,name: '太平區', zip_code: 411, city_id: 3},
      {id: 15 ,name: '中區',   zip_code: 400, city_id: 3},
      {id: 16 ,name: '東區',   zip_code: 401, city_id: 3},
      {id: 17 ,name: '南區',   zip_code: 402, city_id: 3},
      {id: 18 ,name: '西區',   zip_code: 403, city_id: 3},
      {id: 19 ,name: '北區',   zip_code: 404, city_id: 3},
      {id: 20 ,name: '北屯區', zip_code: 406, city_id: 3},
      {id: 21 ,name: '西屯區', zip_code: 407, city_id: 3},
      {id: 22 ,name: '南屯區', zip_code: 408, city_id: 3},
      {id: 23 ,name: '新竹市', zip_code: 300, city_id: 5},
      {id: 24 ,name: '鳳山區', zip_code: 830, city_id: 4},
      {id: 25 ,name: '三民區', zip_code: 807, city_id: 4},
      {id: 26 ,name: '新興區', zip_code: 800, city_id: 4},
      {id: 27 ,name: '前金區', zip_code: 801, city_id: 4},
      {id: 28 ,name: '苓雅區', zip_code: 802, city_id: 4},
      {id: 29 ,name: '鹽埕區', zip_code: 803, city_id: 4},
      {id: 30 ,name: '鼓山區', zip_code: 804, city_id: 4},
      {id: 31 ,name: '旗津區', zip_code: 805, city_id: 4},
      {id: 32 ,name: '前鎮區', zip_code: 806, city_id: 4},
      {id: 33 ,name: '楠梓區', zip_code: 811, city_id: 4},
      {id: 34 ,name: '小港區', zip_code: 812, city_id: 4},
      {id: 35 ,name: '左營區', zip_code: 813, city_id: 4},
      {id: 36 ,name: '萬里區', zip_code: 207, city_id: 6},
      {id: 37 ,name: '金山區', zip_code: 208, city_id: 6},
      {id: 38 ,name: '板橋區', zip_code: 220, city_id: 6},
      {id: 39 ,name: '汐止區', zip_code: 221, city_id: 6},
      {id: 40 ,name: '深坑區', zip_code: 222, city_id: 6},
      {id: 41 ,name: '石碇區', zip_code: 223, city_id: 6},
      {id: 42 ,name: '瑞芳區', zip_code: 224, city_id: 6},
      {id: 43 ,name: '平溪區', zip_code: 226, city_id: 6},
      {id: 44 ,name: '雙溪區', zip_code: 227, city_id: 6},
      {id: 45 ,name: '貢寮區', zip_code: 228, city_id: 6},
      {id: 46 ,name: '新店區', zip_code: 231, city_id: 6},
      {id: 47 ,name: '坪林區', zip_code: 232, city_id: 6},
      {id: 48 ,name: '烏來區', zip_code: 233, city_id: 6},
      {id: 49 ,name: '永和區', zip_code: 234, city_id: 6},
      {id: 50 ,name: '中和區', zip_code: 235, city_id: 6},
      {id: 51 ,name: '土城區', zip_code: 236, city_id: 6},
      {id: 52 ,name: '三峽區', zip_code: 237, city_id: 6},
      {id: 53 ,name: '樹林區', zip_code: 238, city_id: 6},
      {id: 54 ,name: '鶯歌區', zip_code: 239, city_id: 6},
      {id: 55 ,name: '三重區', zip_code: 241, city_id: 6},
      {id: 56 ,name: '新莊區', zip_code: 242, city_id: 6},
      {id: 57 ,name: '泰山區', zip_code: 243, city_id: 6},
      {id: 58 ,name: '林口區', zip_code: 244, city_id: 6},
      {id: 59 ,name: '蘆洲區', zip_code: 247, city_id: 6},
      {id: 60 ,name: '五股區', zip_code: 248, city_id: 6},
      {id: 61 ,name: '八里區', zip_code: 249, city_id: 6},
      {id: 62 ,name: '淡水區', zip_code: 251, city_id: 6},
      {id: 63 ,name: '三芝區', zip_code: 252, city_id: 6},
      {id: 64 ,name: '石門區', zip_code: 253, city_id: 6},
      {id: 65 ,name: '仁武區', zip_code: 814, city_id: 4},
      {id: 66 ,name: '大社區', zip_code: 815, city_id: 4},
      {id: 67 ,name: '岡山區', zip_code: 820, city_id: 4},
      {id: 68 ,name: '路竹區', zip_code: 821, city_id: 4},
      {id: 69 ,name: '橋頭區', zip_code: 825, city_id: 4},
      {id: 70 ,name: '湖內區', zip_code: 829, city_id: 4},
      {id: 71 ,name: '鳥松區', zip_code: 833, city_id: 4},
      {id: 72 ,name: '中西區', zip_code: 700, city_id: 7},
      {id: 73 ,name: '東區',    zip_code: 701, city_id: 7},
      {id: 74 ,name: '南區',   zip_code: 702, city_id: 7},
      {id: 75 ,name: '北區',   zip_code: 704, city_id: 7},
      {id: 76 ,name: '安平區', zip_code: 708, city_id: 7},
      {id: 77 ,name: '安南區', zip_code: 709, city_id: 7},
      {id: 78 ,name: '永康區', zip_code: 710, city_id: 7},
      {id: 79 ,name: '歸仁區', zip_code: 711, city_id: 7},
      {id: 80 ,name: '仁德區', zip_code: 717, city_id: 7},
      {id: 81 ,name: '新市區', zip_code: 744, city_id: 7},
      {id: 82 ,name: '中壢區', zip_code: 320, city_id: 8},
      {id: 83 ,name: '平鎮區', zip_code: 324, city_id: 8},
      {id: 84 ,name: '龍潭區', zip_code: 325, city_id: 8},
      {id: 85 ,name: '桃園區', zip_code: 330, city_id: 8},
      {id: 86 ,name: '八德區', zip_code: 334, city_id: 8},
      {id: 87 ,name: '龜山區', zip_code: 333, city_id: 8},
      {id: 88 ,name: '頭份市', zip_code: 361, city_id: 9}
    ].each do |area|
      Area.create! area
    end
  end
end
